// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mtgroup.auth;

namespace mtgroup.db.Migrations.ContextoAutorizacaoMigrations
{
    [DbContext(typeof(ContextoAutorizacao))]
    [Migration("20201216112719_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("mtgroup.auth.DataModel.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nomeLogin");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SobreNome")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("sistema_usuario_identificador");

                    b.HasIndex("NomeLogin")
                        .IsUnique()
                        .HasDatabaseName("sistema_usuario_nome");

                    b.ToTable("sistema_usuario_conectado");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Usuario01",
                            NomeLogin = "Usuario01",
                            Password = "AQAAAAEAACcQAAAAEAVDkh7tgSGNKE0PAgZge/EAL6OPvnE2MCN2swKjNtt3EGFa/Gvmlfigzqr/4AyMHw=="
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Usuario02",
                            NomeLogin = "Usuario02",
                            Password = "AQAAAAEAACcQAAAAEPZSXLEYeiBQ1wN2eBUjCfPx1qe7z842MdtHVTuTqVVIraplnq7mkoE7DaVkHubjRw=="
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Usuario03",
                            NomeLogin = "Usuario03",
                            Password = "AQAAAAEAACcQAAAAEGN34z8Msov6lRZvtYFPw6O3Fi3wigPbskyNkSKAgh4QpKiYVSm09N2aA1F/yufOUA=="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
